/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    YBtn: typeof import('@yiird/elements')['Btn']
    YCol: typeof import('@yiird/elements')['Col']
    YFooter: typeof import('@yiird/elements')['Footer']
    YFramework: typeof import('@yiird/elements')['Framework']
    YHeader: typeof import('@yiird/elements')['Header']
    YIcon: typeof import('@yiird/elements')['Icon']
    YInput: typeof import('@yiird/elements')['Input']
    YList: typeof import('@yiird/elements')['List']
    YMain: typeof import('@yiird/elements')['Main']
    YPanel: typeof import('@yiird/elements')['Panel']
    YPopover: typeof import('@yiird/elements')['Popover']
    YRow: typeof import('@yiird/elements')['Row']
    YSider: typeof import('@yiird/elements')['Sider']
    YTabs: typeof import('@yiird/elements')['Tabs']
    YTheme: typeof import('@yiird/elements')['Theme']
    YTree: typeof import('@yiird/elements')['Tree']
  }
}
