/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    YBtn: typeof import('./../packages/index.ts')['Btn']
    YCol: typeof import('./../packages/index.ts')['Col']
    YFooter: typeof import('./../packages/index.ts')['Footer']
    YFramework: typeof import('./../packages/index.ts')['Framework']
    YHeader: typeof import('./../packages/index.ts')['Header']
    YIcon: typeof import('./../packages/index.ts')['Icon']
    YMain: typeof import('./../packages/index.ts')['Main']
    YPanel: typeof import('./../packages/index.ts')['Panel']
    YRow: typeof import('./../packages/index.ts')['Row']
    YSider: typeof import('./../packages/index.ts')['Sider']
    YTabs: typeof import('./../packages/index.ts')['Tabs']
    YTheme: typeof import('./../packages/index.ts')['Theme']
    YTree: typeof import('./../packages/index.ts')['Tree']
  }
}
