// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core';
import OButton from 'components/button/o-button.vue';
import OIcon from 'components/icon/o-icon.vue';

declare module '@vue/runtime-core' {
	export interface GlobalComponents {
		OButton: typeof OButton;
		OIcon: typeof OIcon;
	}
}

export {};
