// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module '@vue/runtime-core' {
	export interface GlobalComponents {
		OButton: typeof import('@yiird/owl')['Button'];
		OIcon: typeof import('@yiird/owl')['Icon'];
	}
}

export {};
