import Footer from "./o-footer";
import Header from "./o-header";
import Layout from "./o-layout";
import Main from "./o-main";
import SiderLeft from "./o-sider-left";
import SiderRight from "./o-sider-right";
export * from './definition';
export { Layout, Header, Footer, Main, SiderLeft, SiderRight };
export declare type LayoutInstance = InstanceType<typeof Layout>;
export declare type HeaderInstance = InstanceType<typeof Header>;
export declare type FooterInstance = InstanceType<typeof Footer>;
export declare type MainInstance = InstanceType<typeof Main>;
export declare type SiderLeftInstance = InstanceType<typeof SiderLeft>;
export declare type SiderRightInstance = InstanceType<typeof SiderRight>;
